language: java
jdk:
  - oraclejdk8
# uncomment follow two lines to activate bintray profile for build
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P bintray
script: mvn test -P bintray
